import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PropsWithChildren } from "react";
import "@/sass/globals.sass";
import { NavBarServer } from "@/app/components/shared/NavBar";
import styles from "@/sass/pages/Home.module.sass";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Future Store",
  description: "Generated by create next app"
};

interface RootLayoutProps {
  params: {
    category: string,
    test: string
  };
}

export default function RootLayout({ children }: PropsWithChildren<RootLayoutProps>) {


  return (
    <html lang="en">
    <body className={inter.className}>
    <NavBarServer />
    <section className={styles.content_wrapper}>
      {children}
    </section>
    </body>
    </html>
  );
}
